#02062021:- Write a Basic Python program to Print Triangle (in size of your short finger) on console.
print('                 /|')
print('                / |')
print('               /  |')
print('              /   |')
print('             /    |')
print('            /     |')
print('           /      |')
print('          /       |')
print('         /        |')
print('        /         |')
print('       /          |')
print('      /           |')
print('     /            |')
print('    /             |')
print('   /              |')
print('  /               |')
print(' /              __|')
print('/______________|90|')
